---
- name: Bulk users creation
  hosts: nodes
  vars_files:
    - vars/users.yml
    - vars/password.yml
  tasks:
    - name: Creating users
      user: 
        name: "{{ item }}"
        comment: "{{ item }}@example.com"
        home: "/home/{{ item }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
      with_items:
        - "{{ Username }}"
...
